# Generated by Django 4.1 on 2023-03-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="parts_of_speech",
            field=models.CharField(default="Not Registered", max_length=100),
        ),
    ]
